name: Build Silicate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Позволяет запускать вручную из GitHub UI

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: RelWithDebInfo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: silicate-${{ github.sha }}
          path: build/*.geode
          if-no-files-found: error
